#pragma once

#include "imgui.h"
#include "imgui-SFML.h"

#include "Util/Observer.hpp"
#include "NPC/MatchingEngine.hpp"

namespace RG { namespace View {
    /**
     * \class NPCLog
     * \brief Graphical representation of tredes generated by NPCWorld
     */
    class NPCLog : public Util::Observer {
        public:
            /**
             * \brief Constructor
             *
             * @param matchingEngine pointer to NPC::MatchingEngine used to register as observer
             * 
             */
            NPCLog( NPC::MatchingEngine * matchingEngine );

            /**
             * \brief Clear log
             */
            void    Clear();

            /**
             * \brief Write new log
             */
            void    AddLog(const char* fmt, ...) IM_FMTARGS(2);

            /**
             * \brief Draw log
             */
            void    Draw(const char* title, bool* p_open = NULL, int x = 0, int y = 0);

            /*!
             * This methos is used to recieve nitifikations from NPC::MatchingEngine
             */
            void onNotify(Util::Subject * subject, Util::Event event);
        private:
            ImGuiTextBuffer     Buf;
            ImGuiTextFilter     Filter;
            ImVector<int>       LineOffsets;        // Index to lines offset
            bool                ScrollToBottom;
    };

}}
