libpqxx: pqxx::row Class Reference
pqxx::row Class Reference
Reference to one row in a result.
#include <row.hxx>
Public Types
typedef row_size_type size_type
typedef row_difference_type difference_type
typedef const_row_iterator const_iterator
typedef const_iterator iterator
typedef field reference
typedef const_row_iterator pointer
typedef const_reverse_row_iterator const_reverse_iterator
typedef const_reverse_iterator reverse_iterator
Public Member Functions
row (const result *r, size_t i) PQXX_NOEXCEPT
~row () PQXX_NOEXCEPT
const_iterator begin () const PQXX_NOEXCEPT
const_iterator end () const PQXX_NOEXCEPT
size_type size () const PQXX_NOEXCEPT
void swap (row &) PQXX_NOEXCEPT
size_t rownumber () const PQXX_NOEXCEPT
size_t num () const
row slice (size_type Begin, size_type End) const
PQXX_PURE bool empty () const PQXX_NOEXCEPT
Comparison
PQXX_PURE bool operator== (const row &) const PQXX_NOEXCEPT
bool operator!= (const row &rhs) const PQXX_NOEXCEPT
Field access
reference front () const PQXX_NOEXCEPT
reference back () const PQXX_NOEXCEPT
const_reverse_row_iterator rbegin () const
const_reverse_row_iterator rend () const
reference operator[] (size_type) const PQXX_NOEXCEPT
reference operator[] (int) const PQXX_NOEXCEPT
reference operator[] (const char[]) const
reference operator[] (const std::string &) const
reference at (size_type) const
reference at (int) const
reference at (const char[]) const
reference at (const std::string &) const
Column information
size_type column_number (const std::string &ColName) const
Number of given column (throws exception if it doesn't exist)
size_type column_number (const char[]) const
Number of given column (throws exception if it doesn't exist)
oid column_type (size_type) const
Type of given column.
oid column_type (int ColNum) const
Type of given column.
oid column_type (const std::string &ColName) const
Type of given column.
oid column_type (const char ColName[]) const
Type of given column.
oid column_table (size_type ColNum) const
What table did this column come from?
oid column_table (int ColNum) const
What table did this column come from?
oid column_table (const std::string &ColName) const
What table did this column come from?
size_type table_column (size_type) const
What column number in its table did this result column come from?
size_type table_column (int ColNum) const
What column number in its table did this result column come from?
size_type table_column (const std::string &ColName) const
What column number in its table did this result column come from?
Protected Attributes
const result * m_Home
size_t m_Index
size_type m_Begin
size_type m_End
Friends
class field
Detailed Description
Reference to one row in a result.
A row represents one row (also called a row) in a query result set. It also acts as a container mapping column numbers or names to field values (see below):
cout << row["date"].c_str() << ": " << row["name"].c_str() << endl;
The row itself acts like a (non-modifyable) container, complete with its own const_iterator and const_reverse_iterator.
Member Typedef Documentation
typedef const_row_iterator pqxx::row::const_iterator
typedef const_reverse_row_iterator pqxx::row::const_reverse_iterator
typedef row_difference_type pqxx::row::difference_type
typedef const_iterator pqxx::row::iterator
typedef const_row_iterator pqxx::row::pointer
typedef field pqxx::row::reference
typedef const_reverse_iterator pqxx::row::reverse_iterator
typedef row_size_type pqxx::row::size_type
Constructor & Destructor Documentation
pqxx::row::row (const result * r, size_t i)
Deprecated:
Do not use this constructor. It will become private.
References row().
Referenced by row().
pqxx::row::~row ()
Member Function Documentation
pqxx::field pqxx::row::at (size_type i) const
pqxx::row::reference pqxx::row::at (int i) const
pqxx::field pqxx::row::at (const char f[]) const
Address field by name.
Warning
This is much slower than indexing by number, or iterating.
pqxx::row::reference pqxx::row::at (const std::string & s) const
Address field by name.
Warning
This is much slower than indexing by number, or iterating.
pqxx::row::reference pqxx::row::back () const
pqxx::row::const_iterator pqxx::row::begin () const
size_type pqxx::row::column_number (const std::string & ColName) const
Number of given column (throws exception if it doesn't exist)
pqxx::row::size_type pqxx::row::column_number (const char ColName[]) const
Number of given column (throws exception if it doesn't exist)
References pqxx::result::column_number().
pqxx::oid pqxx::row::column_table (size_type ColNum) const
What table did this column come from?
oid pqxx::row::column_table (int ColNum) const
What table did this column come from?
oid pqxx::row::column_table (const std::string & ColName) const
What table did this column come from?
pqxx::oid pqxx::row::column_type (size_type ColNum) const
Type of given column.
oid pqxx::row::column_type (int ColNum) const
Type of given column.
oid pqxx::row::column_type (const std::string & ColName) const
Type of given column.
oid pqxx::row::column_type (const char ColName[]) const
Type of given column.
bool pqxx::row::empty () const
pqxx::row::const_iterator pqxx::row::end () const
pqxx::row::reference pqxx::row::front () const
size_t pqxx::row::num () const
Referenced by pqxx::const_result_iterator::operator-().
bool pqxx::row::operator!= (const row & rhs) const
bool pqxx::row::operator== (const row & rhs) const
pqxx::row::reference pqxx::row::operator[] (size_type i) const
pqxx::row::reference pqxx::row::operator[] (int i) const
pqxx::row::reference pqxx::row::operator[] (const char f[]) const
Address field by name.
Warning
This is much slower than indexing by number, or iterating.
pqxx::row::reference pqxx::row::operator[] (const std::string & s) const
Address field by name.
Warning
This is much slower than indexing by number, or iterating.
pqxx::row::const_reverse_iterator pqxx::row::rbegin () const
pqxx::row::const_reverse_iterator pqxx::row::rend () const
size_t pqxx::row::rownumber () const
size_type pqxx::row::size () const
pqxx::row pqxx::row::slice (size_type Begin, size_type End) const
Produce a slice of this row, containing the given range of columns.
The slice runs from the range's starting column to the range's end column, exclusive. It looks just like a normal result row, except slices can be empty.
Warning
Slicing is a relatively new feature, and not all software may be prepared to deal with empty slices. If there is any chance that your program might be creating empty slices and passing them to code that may not be designed with the possibility of empty rows in mind, be sure to test for that case.
References m_Begin, and m_End.
void pqxx::row::swap (row & rhs)
pqxx::row::size_type pqxx::row::table_column (size_type ColNum) const
What column number in its table did this result column come from?
A meaningful answer can be given only if the column in question comes directly from a column in a table. If the column is computed in any other way, a logic_error will be thrown.
Parameters
ColNum a zero-based column number in this result set
Returns
a zero-based column number in originating table
size_type pqxx::row::table_column (int ColNum) const
What column number in its table did this result column come from?
size_type pqxx::row::table_column (const std::string & ColName) const
What column number in its table did this result column come from?
Friends And Related Function Documentation
friend class field friend
Member Data Documentation
size_type pqxx::row::m_Begin protected
Referenced by slice().
size_type pqxx::row::m_End protected
Referenced by slice().
const result* pqxx::row::m_Home protected
size_t pqxx::row::m_Index protected
The documentation for this class was generated from the following files:
row.hxx
row.cxx