libpqxx: pqxx::tablestream Class Reference
pqxx::tablestream Class Reference abstract
#include <tablestream.hxx>
Public Member Functions
tablestream (transaction_base &Trans, const std::string &Null=std::string())
virtual ~tablestream () PQXX_NOEXCEPT=0
virtual void complete ()=0
Public Member Functions inherited from pqxx::internal::transactionfocus
transactionfocus (transaction_base &t)
Public Member Functions inherited from pqxx::internal::namedclass
namedclass (const std::string &Classname, const std::string &Name="")
const std::string & name () const PQXX_NOEXCEPT
const std::string & classname () const PQXX_NOEXCEPT
std::string description () const
Protected Member Functions
const std::string & NullStr () const
bool is_finished () const PQXX_NOEXCEPT
void base_close ()
Protected Member Functions inherited from pqxx::internal::transactionfocus
void register_me ()
void unregister_me () PQXX_NOEXCEPT
void reg_pending_error (const std::string &) PQXX_NOEXCEPT
bool registered () const PQXX_NOEXCEPT
Static Protected Member Functions
template<typename ITER >
static std::string columnlist (ITER colbegin, ITER colend)
Additional Inherited Members
Protected Attributes inherited from pqxx::internal::transactionfocus
transaction_base & m_Trans
Detailed Description
Deprecated:
Base class for obsolete tablereader/tablewriter classes.
Constructor & Destructor Documentation
pqxx::tablestream::tablestream (transaction_base & Trans, const std::string & Null = std::string()) explicit
References tablestream().
Referenced by tablestream().
pqxx::tablestream::~tablestream () pure virtual
Member Function Documentation
void pqxx::tablestream::base_close () protected
template<typename ITER > std::string pqxx::tablestream::columnlist (ITER colbegin, ITER colend) static protected
References pqxx::separated_list().
Referenced by pqxx::tablereader::tablereader(), and pqxx::tablewriter::tablewriter().
virtual void pqxx::tablestream::complete () pure virtual
Implemented in pqxx::tablewriter, and pqxx::tablereader.
bool pqxx::tablestream::is_finished () const protected
const std::string& pqxx::tablestream::NullStr () const protected
Referenced by pqxx::tablewriter::generate().
The documentation for this class was generated from the following files:
tablestream.hxx
tablestream.cxx