libpqxx: pqxx::internal::sql_cursor Class Reference
pqxx::internal::sql_cursor Class Reference
Cursor with SQL positioning semantics.
#include <cursor.hxx>
Public Member Functions
sql_cursor (transaction_base &t, const std::string &query, const std::string &cname, cursor_base::accesspolicy ap, cursor_base::updatepolicy up, cursor_base::ownershippolicy op, bool hold)
sql_cursor (transaction_base &t, const std::string &cname, cursor_base::ownershippolicy op)
~sql_cursor () PQXX_NOEXCEPT
result fetch (difference_type rows, difference_type &displacement)
result fetch (difference_type rows)
difference_type move (difference_type rows, difference_type &displacement)
difference_type move (difference_type rows)
difference_type pos () const PQXX_NOEXCEPT
Current position, or -1 for unknown.
difference_type endpos () const PQXX_NOEXCEPT
End position, or -1 for unknown.
const result & empty_result () const PQXX_NOEXCEPT
Return zero-row result for this cursor.
void close () PQXX_NOEXCEPT
Public Member Functions inherited from pqxx::cursor_base
const std::string & name () const PQXX_NOEXCEPT
Name of underlying SQL cursor.
Additional Inherited Members
Public Types inherited from pqxx::cursor_base
enum accesspolicy { forward_only, random_access }
Cursor access-pattern policy.
enum updatepolicy { read_only, update }
Cursor update policy.
enum ownershippolicy { owned, loose }
Cursor destruction policy.
typedef result::size_type size_type
typedef result::difference_type difference_type
Static Public Member Functions inherited from pqxx::cursor_base
static difference_type all () PQXX_NOEXCEPT
Special value: read until end.
static difference_type next () PQXX_NOEXCEPT
Special value: read one row only.
static difference_type prior () PQXX_NOEXCEPT
Special value: read backwards, one row only.
static difference_type backward_all () PQXX_NOEXCEPT
Special value: read backwards from current position back to origin.
Protected Member Functions inherited from pqxx::cursor_base
cursor_base (connection_base &, const std::string &Name, bool embellish_name=true)
Protected Attributes inherited from pqxx::cursor_base
const std::string m_name
Detailed Description
Cursor with SQL positioning semantics.
Thin wrapper around an SQL cursor, with SQL's ideas of positioning.
SQL cursors have pre-increment/pre-decrement semantics, with on either end of the result set a special position that does not repesent a row. This class models SQL cursors for the purpose of implementing more C++-like semantics on top.
Positions of actual rows are numbered starting at 1. Position 0 exists but does not refer to a row. There is a similar non-row position at the end of the result set.
Don't use this at home. You deserve better. Use the stateles_cursor instead.
Constructor & Destructor Documentation
pqxx::internal::sql_cursor::sql_cursor (transaction_base & t, const std::string & query, const std::string & cname, cursor_base::accesspolicy ap, cursor_base::updatepolicy up, cursor_base::ownershippolicy op, bool hold)
References pqxx::connection_base::activate(), pqxx::transaction_base::conn(), pqxx::transaction_base::exec(), pqxx::cursor_base::forward_only, pqxx::cursor_base::name(), and pqxx::cursor_base::update.
pqxx::internal::sql_cursor::sql_cursor (transaction_base & t, const std::string & cname, cursor_base::ownershippolicy op)
References pqxx::transaction_base::conn(), and pqxx::cursor_base::owned.
pqxx::internal::sql_cursor::~sql_cursor ()
Member Function Documentation
void pqxx::internal::sql_cursor::close ()
References pqxx::cursor_base::loose, and pqxx::cursor_base::owned.
const result& pqxx::internal::sql_cursor::empty_result () const
Return zero-row result for this cursor.
Referenced by pqxx::internal::stateless_cursor_retrieve().
difference_type pqxx::internal::sql_cursor::endpos () const
End position, or -1 for unknown.
Returns the final position, just after the last row in the result set. The starting position, just before the first row, counts as position zero.
End position is unknown until it is encountered during use.
Referenced by pqxx::internal::obtain_stateless_cursor_size().
result pqxx::internal::sql_cursor::fetch (difference_type rows, difference_type & displacement)
Referenced by pqxx::internal::stateless_cursor_retrieve().
result pqxx::internal::sql_cursor::fetch (difference_type rows)
difference_type pqxx::internal::sql_cursor::move (difference_type rows, difference_type & displacement)
Referenced by pqxx::internal::obtain_stateless_cursor_size(), and pqxx::internal::stateless_cursor_retrieve().
difference_type pqxx::internal::sql_cursor::move (difference_type rows)
difference_type pqxx::internal::sql_cursor::pos () const
Current position, or -1 for unknown.
The starting position, just before the first row, counts as position zero.
Position may be unknown if (and only if) this cursor was adopted, and has never hit its starting position (position zero).
Referenced by pqxx::internal::stateless_cursor_retrieve().
The documentation for this class was generated from the following files:
cursor.hxx
cursor.cxx